name: Format

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.3.9
      - run: flutter pub get

      # Run the formatter
      - name: Format code
        run: flutter format --set-exit-if-changed .
